import type { QueueItem, GrievanceStatusResponse } from './types'

const now = new Date()
const h = (hrs: number) => new Date(now.getTime() - hrs * 3_600_000).toISOString()
const due = (hrs: number) => new Date(now.getTime() + hrs * 3_600_000).toISOString()
const overdue = (hrs: number) => new Date(now.getTime() - hrs * 3_600_000).toISOString()

export const MOCK_QUEUE: QueueItem[] = [
  {
    tracking_id: 'GRV-10023',
    status: 'in_progress',
    category: 'roads',
    priority: 'critical',
    department: 'Roads',
    summary: 'Large pothole on MG Road near City Mall causing accidents daily',
    confidence: 0.91,
    needs_human_review: false,
    created_at: h(10),
    sla_due_at: due(2),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10024',
    status: 'resolved',
    category: 'water_supply',
    priority: 'high',
    department: 'Water Board',
    summary: 'No water supply in Koramangala 5th Block for 3 days',
    confidence: 0.88,
    needs_human_review: false,
    created_at: h(48),
    sla_due_at: due(0),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10025',
    status: 'new',
    category: 'sanitation',
    priority: 'high',
    department: 'Sanitation',
    summary: 'Garbage not collected for 5 days in HSR Layout Sector 2',
    confidence: 0.52,
    needs_human_review: true,
    created_at: h(5),
    sla_due_at: due(19),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10026',
    status: 'escalated',
    category: 'electricity',
    priority: 'critical',
    department: 'Electricity',
    summary: 'Power outage in entire Jayanagar 4th block — transformers down',
    confidence: 0.94,
    needs_human_review: false,
    created_at: h(6),
    sla_due_at: overdue(2),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10027',
    status: 'assigned',
    category: 'drainage',
    priority: 'medium',
    department: 'Sanitation',
    summary: 'Overflowing drain on 80ft road causing flooding during rain',
    confidence: 0.47,
    needs_human_review: true,
    created_at: h(12),
    sla_due_at: due(12),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10028',
    status: 'new',
    category: 'streetlights',
    priority: 'low',
    department: 'Electricity',
    summary: 'Street lights not working on entire stretch of Residency Road',
    confidence: 0.83,
    needs_human_review: false,
    created_at: h(2),
    sla_due_at: due(46),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10029',
    status: 'in_progress',
    category: 'garbage',
    priority: 'medium',
    department: 'Sanitation',
    summary: 'Illegal garbage dumping near Ulsoor Lake creating health hazard',
    confidence: 0.79,
    needs_human_review: false,
    created_at: h(24),
    sla_due_at: due(5),
    parent_tracking_id: 'GRV-10030',
  },
  {
    tracking_id: 'GRV-10030',
    status: 'in_progress',
    category: 'parks',
    priority: 'low',
    department: 'Parks',
    summary: 'Multiple issues near Ulsoor Lake — garbage and broken benches',
    confidence: 0.71,
    needs_human_review: false,
    created_at: h(24),
    sla_due_at: due(48),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10031',
    status: 'reopened',
    category: 'water_supply',
    priority: 'high',
    department: 'Water Board',
    summary: 'Contaminated water supply in Indiranagar — brown water from taps',
    confidence: 0.58,
    needs_human_review: true,
    created_at: h(36),
    sla_due_at: overdue(5),
    parent_tracking_id: null,
  },
  {
    tracking_id: 'GRV-10032',
    status: 'closed',
    category: 'roads',
    priority: 'medium',
    department: 'Roads',
    summary: 'Missing manhole cover on 100ft Road near petrol bunk',
    confidence: 0.86,
    needs_human_review: false,
    created_at: h(72),
    sla_due_at: null,
    parent_tracking_id: null,
  },
]

export const MOCK_DETAILS: Record<string, GrievanceStatusResponse> = {
  'GRV-10023': {
    tracking_id: 'GRV-10023',
    status: 'in_progress',
    category: 'roads',
    priority: 'critical',
    department: 'Roads',
    summary: 'Large pothole on MG Road near City Mall causing accidents daily',
    address: 'MG Road, near City Mall, Bengaluru',
    confidence: 0.91,
    created_at: h(10),
    sla_due_at: due(2),
    timeline: [
      { status: 'new', note: 'Grievance created via intake', at: h(10) },
      { status: 'assigned', note: 'Assigned to Roads department', at: h(9) },
      { status: 'in_progress', note: 'Team dispatched to location', at: h(3) },
    ],
    subtasks: [],
    media: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=600' },
    ],
  },
  'GRV-10026': {
    tracking_id: 'GRV-10026',
    status: 'escalated',
    category: 'electricity',
    priority: 'critical',
    department: 'Electricity',
    summary: 'Power outage in entire Jayanagar 4th block — transformers down',
    address: 'Jayanagar 4th Block, Bengaluru',
    confidence: 0.94,
    created_at: h(6),
    sla_due_at: overdue(2),
    timeline: [
      { status: 'new', note: 'Grievance created via intake', at: h(6) },
      { status: 'assigned', note: 'Assigned to Electricity department', at: h(5) },
      { status: 'escalated', note: 'SLA breached — auto-escalated by system', at: h(0) },
    ],
    subtasks: [],
    media: [],
  },
  'GRV-10030': {
    tracking_id: 'GRV-10030',
    status: 'in_progress',
    category: 'parks',
    priority: 'low',
    department: 'Parks',
    summary: 'Multiple issues near Ulsoor Lake — garbage and broken benches',
    address: 'Ulsoor Lake, Bengaluru',
    confidence: 0.71,
    created_at: h(24),
    sla_due_at: due(48),
    timeline: [
      { status: 'new', note: 'Parent grievance created via intake; split into 2 departments', at: h(24) },
      { status: 'in_progress', note: 'Sub-issues dispatched', at: h(20) },
    ],
    subtasks: [
      { tracking_id: 'GRV-10029', department: 'Sanitation', status: 'in_progress' },
    ],
    media: [],
  },
}

// Fallback detail for any tracking_id not in MOCK_DETAILS
export function getMockDetail(trackingId: string): GrievanceStatusResponse {
  if (MOCK_DETAILS[trackingId]) return MOCK_DETAILS[trackingId]

  const item = MOCK_QUEUE.find(q => q.tracking_id === trackingId)
  if (!item) throw new Error(`Grievance ${trackingId} not found`)

  return {
    tracking_id: item.tracking_id,
    status: item.status,
    category: item.category,
    priority: item.priority,
    department: item.department,
    summary: item.summary,
    address: 'Bengaluru, Karnataka',
    confidence: item.confidence,
    created_at: item.created_at,
    sla_due_at: item.sla_due_at,
    timeline: [
      { status: 'new', note: 'Grievance created via intake', at: item.created_at },
      ...(item.status !== 'new'
        ? [{ status: item.status, note: `Status updated to ${item.status}`, at: h(1) }]
        : []),
    ],
    subtasks: [],
    media: [],
  }
}
